"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const todo_controllers_1 = require("../controllers/todo-controllers");
const router = (0, express_1.Router)();
router.get('/todo', todo_controllers_1.getTodo);
router.post('/todo', todo_controllers_1.postTodo);
router.put('/todo/:todoId', todo_controllers_1.putTodo);
router.delete('/todo/:todoId', todo_controllers_1.deleteTodo);
exports.default = router;
